stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo " preparing test data"
  script:
    - echo "Running unit tests..."
  after_script:
    - echo " cleaning up temporary files"


run_lint_tests:
  stage: test
  before_script:
    - echo " preparing test data"
  script:
    - echo "Running tests..."
  after_script:
    - echo " cleaning up temporary files"

build_image:
  stage: build
  script:
    - echo " Building the docker image"
    - echo " tagging the docker image"

push_image:
  stage: build
  script:
    - echo "Logging the docker registry"
    - echo " Pushing docker image to registry"
  
deploy_image:
  stage: deploy
  - echo " deploying new docker image to server"
